<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - TestTest</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>TestTest</h1>
<p>
  Test duration: 73,503s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">test.java.TestTest</td>
      </tr>
            
<tr>
  <td class="method">
                  testHbogoWebdriverTest1
      </td>
  <td class="duration">
    25,883s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        Verification is not successfull<br>
                                <a href="/Users/georgegaspar/Documents/Tests/*firefox-2015-0-31-16-7-37-565.png"><p align="left"Element screenshot at Sat Jan 31 16:07:39 CET 2015</p>
                                <p><img width="50%" src="/Users/georgegaspar/Documents/Tests/*firefox-2015-0-31-16-7-37-565.png" alt="screenshot at Sat Jan 31 16:07:39 CET 2015"/></p></a><br />
                                Completed executing following method : TestTest.testHbogoWebdriverTest1<br>
                                Completed executing following method : TestTest.testHbogoWebdriverTest1<br>
                                <a href="/Users/georgegaspar/Documents/Tests/*firefox-testHbogoWebdriverTest1(test.java.TestTest)-2015-0-31-16-7-53-792.png"><p align="left">Error screenshot at Sat Jan 31 16:07:55 CET 2015</p>
                                <p><img width="50%" src="/Users/georgegaspar/Documents/Tests/*firefox-testHbogoWebdriverTest1(test.java.TestTest)-2015-0-31-16-7-53-792.png" alt="screenshot at Sat Jan 31 16:07:55 CET 2015"/></p></a><br />
                                Test Method resides in test.java.TestTest<br>
                                <p>Test Status: </p><p>Failed</p>
                                About to begin executing following method : TestTest.tearDown<br>
                                About to begin executing following method : TestTest.tearDown<br>
                  </div>
    

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (3)<br/>
(1)java.lang.AssertionError:expected [true] but found [false]<br/>
(2)java.lang.AssertionError:expected [HB. Brhol. Bármikor] but found [HBO GO. Bárhol. Bármikor.]<br/>
(3)org.openqa.selenium.WebDriverException:CustomerManager.customer is null<br/>
Command duration or timeout: 24 milliseconds<br/>
Build info: version: &apos;2.44.0&apos;, revision: &apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&apos;, time: &apos;2014-10-23 13:11:40&apos;<br/>
System info: host: &apos;igeorge.local&apos;, ip: &apos;192.168.1.108&apos;, os.name: &apos;Mac OS X&apos;, os.arch: &apos;x86_64&apos;, os.version: &apos;10.7.5&apos;, java.version: &apos;1.8.0_25&apos;<br/>
Driver info: org.openqa.selenium.firefox.FirefoxDriver<br/>
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=35.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]<br/>
Session ID: 40281a30-e0b6-2f41-9416-8e760ba53b7f<br/>
<br/>
Failure 1 of 3<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertTrue(Assert.java:42)<br/>
	at org.testng.Assert.assertTrue(Assert.java:52)<br/>
	at test.java.TestBase.assertTrue(TestBase.java:17)<br/>
	at test.java.TestBase.verifySuccess(TestBase.java:58)<br/>
	at test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:78)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:483)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br/>
	at org.testng.TestNG.run(TestNG.java:1057)<br/>
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br/>
<br/>
Failure 2 of 3<br/>
java.lang.AssertionError: expected [HB. Brhol. Bármikor] but found [HBO GO. Bárhol. Bármikor.]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at test.java.TestBase.assertEquals(TestBase.java:37)<br/>
	at test.java.TestBase.verifyEquals(TestBase.java:105)<br/>
	at test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:80)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:483)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br/>
	at org.testng.TestNG.run(TestNG.java:1057)<br/>
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br/>
<br/>
Failure 3 of 3<br/>
org.openqa.selenium.WebDriverException: CustomerManager.customer is null<br/>
Command duration or timeout: 24 milliseconds<br/>
Build info: version: &apos;2.44.0&apos;, revision: &apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&apos;, time: &apos;2014-10-23 13:11:40&apos;<br/>
System info: host: &apos;igeorge.local&apos;, ip: &apos;192.168.1.108&apos;, os.name: &apos;Mac OS X&apos;, os.arch: &apos;x86_64&apos;, os.version: &apos;10.7.5&apos;, java.version: &apos;1.8.0_25&apos;<br/>
Driver info: org.openqa.selenium.firefox.FirefoxDriver<br/>
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=35.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]<br/>
Session ID: 40281a30-e0b6-2f41-9416-8e760ba53b7f</b></a><br />
    <div class="stackTrace" id="exception-0">
              sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br />
              sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br />
              sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br />
              java.lang.reflect.Constructor.newInstance(Constructor.java:408)<br />
              org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)<br />
              org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)<br />
              org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)<br />
              org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)<br />
              test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:166)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:483)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  testHbogoWebdriverTest1
      </td>
  <td class="duration">
    29,404s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        Verification is not successfull<br>
                                <a href="/Users/georgegaspar/Documents/Tests/*firefox-2015-0-31-16-8-13-911.png"><p align="left"Element screenshot at Sat Jan 31 16:08:15 CET 2015</p>
                                <p><img width="50%" src="/Users/georgegaspar/Documents/Tests/*firefox-2015-0-31-16-8-13-911.png" alt="screenshot at Sat Jan 31 16:08:15 CET 2015"/></p></a><br />
                                Completed executing following method : TestTest.testHbogoWebdriverTest1<br>
                                Completed executing following method : TestTest.testHbogoWebdriverTest1<br>
                                <a href="/Users/georgegaspar/Documents/Tests/*firefox-testHbogoWebdriverTest1(test.java.TestTest)-2015-0-31-16-8-30-48.png"><p align="left">Error screenshot at Sat Jan 31 16:08:31 CET 2015</p>
                                <p><img width="50%" src="/Users/georgegaspar/Documents/Tests/*firefox-testHbogoWebdriverTest1(test.java.TestTest)-2015-0-31-16-8-30-48.png" alt="screenshot at Sat Jan 31 16:08:31 CET 2015"/></p></a><br />
                                Test Method resides in test.java.TestTest<br>
                                <p>Test Status: </p><p>Failed</p>
                                About to begin executing following method : TestTest.tearDown<br>
                                About to begin executing following method : TestTest.tearDown<br>
                  </div>
    

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (3)<br/>
(1)java.lang.AssertionError:expected [true] but found [false]<br/>
(2)java.lang.AssertionError:expected [HB. Brhol. Bármikor] but found [HBO GO. Bárhol. Bármikor.]<br/>
(3)org.openqa.selenium.WebDriverException:CustomerManager.customer is null<br/>
Command duration or timeout: 20 milliseconds<br/>
Build info: version: &apos;2.44.0&apos;, revision: &apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&apos;, time: &apos;2014-10-23 13:11:40&apos;<br/>
System info: host: &apos;igeorge.local&apos;, ip: &apos;192.168.1.108&apos;, os.name: &apos;Mac OS X&apos;, os.arch: &apos;x86_64&apos;, os.version: &apos;10.7.5&apos;, java.version: &apos;1.8.0_25&apos;<br/>
Driver info: org.openqa.selenium.firefox.FirefoxDriver<br/>
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=35.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]<br/>
Session ID: 30102a37-bb7d-1748-aefd-0f1b24d8f2f7<br/>
<br/>
Failure 1 of 3<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertTrue(Assert.java:42)<br/>
	at org.testng.Assert.assertTrue(Assert.java:52)<br/>
	at test.java.TestBase.assertTrue(TestBase.java:17)<br/>
	at test.java.TestBase.verifySuccess(TestBase.java:58)<br/>
	at test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:78)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:483)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br/>
	at org.testng.TestNG.run(TestNG.java:1057)<br/>
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br/>
<br/>
Failure 2 of 3<br/>
java.lang.AssertionError: expected [HB. Brhol. Bármikor] but found [HBO GO. Bárhol. Bármikor.]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at test.java.TestBase.assertEquals(TestBase.java:37)<br/>
	at test.java.TestBase.verifyEquals(TestBase.java:105)<br/>
	at test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:80)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:483)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br/>
	at org.testng.TestNG.run(TestNG.java:1057)<br/>
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br/>
<br/>
Failure 3 of 3<br/>
org.openqa.selenium.WebDriverException: CustomerManager.customer is null<br/>
Command duration or timeout: 20 milliseconds<br/>
Build info: version: &apos;2.44.0&apos;, revision: &apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&apos;, time: &apos;2014-10-23 13:11:40&apos;<br/>
System info: host: &apos;igeorge.local&apos;, ip: &apos;192.168.1.108&apos;, os.name: &apos;Mac OS X&apos;, os.arch: &apos;x86_64&apos;, os.version: &apos;10.7.5&apos;, java.version: &apos;1.8.0_25&apos;<br/>
Driver info: org.openqa.selenium.firefox.FirefoxDriver<br/>
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=35.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]<br/>
Session ID: 30102a37-bb7d-1748-aefd-0f1b24d8f2f7</b></a><br />
    <div class="stackTrace" id="exception-1">
              sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br />
              sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br />
              sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br />
              java.lang.reflect.Constructor.newInstance(Constructor.java:408)<br />
              org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)<br />
              org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)<br />
              org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)<br />
              org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)<br />
              test.java.TestTest.testHbogoWebdriverTest1(TestTest.java:166)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:483)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
          <tr>
        <td colspan="3" class="group">test.java.TestTest2</td>
      </tr>
            
<tr>
  <td class="method">
                  test1
      </td>
  <td class="duration">
    3,658s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        Verification is successfull<br>
                                JavaScript text:hello world<br>
                                <p>Test done</p>
                                Completed executing following method : TestTest2.test1<br>
                                Completed executing following method : TestTest2.test1<br>
                                <a href="/Users/georgegaspar/Documents/Tests/*firefox-test1(test.java.TestTest2)-2015-0-31-16-8-40-123.png"><p align="left">Error screenshot at Sat Jan 31 16:08:40 CET 2015</p>
                                <p><img width="50%" src="/Users/georgegaspar/Documents/Tests/*firefox-test1(test.java.TestTest2)-2015-0-31-16-8-40-123.png" alt="screenshot at Sat Jan 31 16:08:40 CET 2015"/></p></a><br />
                                Test Method resides in test.java.TestTest2<br>
                                <p>Test Status: </p><p>Failed</p>
                                About to begin executing following method : TestTest2.tearDown<br>
                                About to begin executing following method : TestTest2.tearDown<br>
                  </div>
    

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (1)<br/>
(1)java.lang.AssertionError:expected [Hello-Bello] but found [Google]<br/>
<br/>
Failure 1 of 1<br/>
java.lang.AssertionError: expected [Hello-Bello] but found [Google]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:165)<br />
              test.java.TestBase.assertEquals(TestBase.java:37)<br />
              test.java.TestBase.verifyEquals(TestBase.java:105)<br />
              test.java.TestTest2.test1(TestTest2.java:84)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:483)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
