<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test on Chrome"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="16.717">
  <properties />
            <testcase name="closeBrowser" time="0.000" classname="test.java.TestHboSignIn">
                <failure type="java.io.FileNotFoundException"
                  message="\Library\WebServer\DocumentsSSL\testNG\har.har (A rendszer nem találja a megadott elérési utat)"
              >
<![CDATA[java.io.FileNotFoundException: \Library\WebServer\DocumentsSSL\testNG\har.har (A rendszer nem találja a megadott elérési utat)
  java.io.FileOutputStream.open(Native Method)
  java.io.FileOutputStream.<init>(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  main.java.qa.framework.main.TestBase.copyDirectory(TestBase.java:791)
  main.java.qa.framework.main.TestBase.copyDirectory(TestBase.java:786)
  main.java.qa.framework.main.TestBase.closeBrowser(TestBase.java:143)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:225)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:114)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testSignInSuccess" time="16.717" classname="test.java.TestHboSignIn" />
      
</testsuite>
